    
#FROM centos
#RUN yum update -y

FROM ubuntu:trusty
RUN echo 'I like Docker, and it works!'

#CMD ["executable","param1","param2"]
CMD ping localhost

## or, using ENTRYPOINT, you can do something like this:
##
##ENTRYPOINT ["/bin/ping","-c","3"]
##CMD ["localhost"]
##

